from pydantic import BaseModel, ConfigDict, Field


class QueryRequest(BaseModel):
    """
    Request model for the banking assistant.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    query: str = Field(
        ...,
        min_length=1,
        description="Banking question",
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of retrieved documents",
    )


class Source(BaseModel):
    """
    Source information returned by the RAG agent.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    source: str = Field(
        default="",
        description="Source document name",
    )

    page: int | None = Field(
        default=None,
        description="Page number if available",
    )


class Metadata(BaseModel):
    """
    Metadata returned with the AI response.

    OpenAI structured outputs require object schemas
    to explicitly disallow additional properties.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    route: str | None = None

    retrieval_count: int | None = None

    confidence: float | None = None


class AIResponse(BaseModel):
    """
    Structured response generated by the banking agent.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    answer: str = Field(
        ...,
        description="Final answer to the banking question",
    )

    route: str = Field(
        ...,
        description="Agent route used to answer the question",
    )

    sources: list[Source] = Field(
        default_factory=list,
        description="Sources used to generate the answer",
    )

    metadata: Metadata = Field(
        default_factory=Metadata,
        description="Additional response metadata",
    )


class QueryResponse(AIResponse):
    """
    Backward-compatible response schema.

    Existing imports in src.api.v1.schemas.__init__
    expect QueryResponse to exist.
    """

    pass