from typing import Any

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """
    Request model for the Smart Banking Assistant.
    """

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Natural-language banking question.",
        examples=[
            "What is the home loan interest rate?"
        ],
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of documents to retrieve.",
    )


class AIResponse(BaseModel):
    """
    Standard response generated by the Smart Banking Assistant agent.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the AI assistant.",
    )

    sources: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Sources used to generate the answer.",
    )

    route: str | None = Field(
        default=None,
        description="Agent route used to answer the query.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional response metadata.",
    )


class QueryResponse(BaseModel):
    """
    API response returned to the client.
    """

    query: str = Field(
        ...,
        description="Original user query.",
    )

    answer: str | None = Field(
        default=None,
        description="Final answer generated by the assistant.",
    )

    route: str | None = Field(
        default=None,
        description="Route selected by the LangGraph agent.",
    )

    sources: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Retrieved source documents.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional agent metadata.",
    )